#!/bin/sh


			if [ ! -f /etc/inited ]; then
				[ uci get dhcp.@dnsmasq[0].noresolv ] && {
					uci del dhcp.@dnsmasq[0].noresolv
					uci commit dhcp
					service dnsmasq reload
				}
			fi
count=0
while :; do
	ping -c 1 www.baidu.com >/dev/null 2>&1
	if [ "$?" == "0" ]; then
		ping -c 1 cdn.qqcn.xyz >/dev/null 2>&1
		if [ "$?" == "0" ]; then
			opkg update
			# if [ ! -f /etc/inited ]; then
				[ uci get dhcp.@dnsmasq[0].noresolv ] && {
					uci del dhcp.@dnsmasq[0].noresolv
					uci commit dhcp
					service dnsmasq reload
				}

				cp -r /etc/config /etc/confbak

				[ -f "/etc/config/installed-opkg" ] && {
					for ipk in $(cat /etc/config/installed-opkg); do
						opkg upgrade --force-overwrite --force-checksum $ipk
					done
					rm -f /etc/config/installed-opkg
				} || {
					for ipk in $(cat /etc/backup/installed_packages.txt | grep -oE '.*overlay' | awk '{print $1}'); do
						opkg upgrade --force-overwrite --force-checksum $ipk
					done
				}
				sysupgrade -k -l >/dev/null 2>&1
				rm /etc/config/.*-opkg
				opkg install >/dev/null 2>&1
			# fi
			rm -f /var/lock/opkg.lock
			touch /etc/inited
			break
		fi
	fi
	sleep 5
	count=$((count + 1))
	if [ $count -gt 120 ]; then
		break
	fi
done

